# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vincent/Desktop/my_client/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 837)
        MainWindow.setMinimumSize(QtCore.QSize(1389, 837))
        MainWindow.setMaximumSize(QtCore.QSize(1389, 837))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.cmdBrowser.setGeometry(QtCore.QRect(10, 40, 1371, 181))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cmdBrowser.setFont(font)
        self.cmdBrowser.setObjectName("cmdBrowser")
        self.folderWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.folderWidget.setGeometry(QtCore.QRect(700, 270, 681, 511))
        self.folderWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.folderWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.folderWidget.setObjectName("folderWidget")
        self.folderWidget.setColumnCount(5)
        self.folderWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(4, item)
        self.folderWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.folderWidget.horizontalHeader().setDefaultSectionSize(150)
        self.folderWidget.horizontalHeader().setMinimumSectionSize(19)
        self.folderWidget.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 230, 681, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.navigationBar = QtWidgets.QLineEdit(self.layoutWidget)
        self.navigationBar.setObjectName("navigationBar")
        self.horizontalLayout.addWidget(self.navigationBar)
        self.goButton = QtWidgets.QPushButton(self.layoutWidget)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout.addWidget(self.goButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 1371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(720, 5, 93, 32))
        self.connectButton.setObjectName("connectButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 9, 688, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ipInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ipInput.setObjectName("ipInput")
        self.horizontalLayout_2.addWidget(self.ipInput)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.portInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.portInput.setObjectName("portInput")
        self.horizontalLayout_2.addWidget(self.portInput)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.userInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.userInput.setObjectName("userInput")
        self.horizontalLayout_2.addWidget(self.userInput)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.passwordInput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.passwordInput.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.horizontalLayout_2.addWidget(self.passwordInput)
        self.folderWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.folderWidget_2.setGeometry(QtCore.QRect(10, 270, 681, 511))
        self.folderWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.folderWidget_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.folderWidget_2.setObjectName("folderWidget_2")
        self.folderWidget_2.setColumnCount(5)
        self.folderWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget_2.setHorizontalHeaderItem(4, item)
        self.folderWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.folderWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.folderWidget_2.horizontalHeader().setMinimumSectionSize(19)
        self.folderWidget_2.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 230, 681, 33))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.navigationBar_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.navigationBar_2.setText("")
        self.navigationBar_2.setObjectName("navigationBar_2")
        self.horizontalLayout_3.addWidget(self.navigationBar_2)
        self.goButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.goButton_2.setObjectName("goButton_2")
        self.horizontalLayout_3.addWidget(self.goButton_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionPassive = QtWidgets.QAction(MainWindow)
        self.actionPassive.setObjectName("actionPassive")
        self.actionPort = QtWidgets.QAction(MainWindow)
        self.actionPort.setObjectName("actionPort")
        self.actionSYSTEM = QtWidgets.QAction(MainWindow)
        self.actionSYSTEM.setObjectName("actionSYSTEM")
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.actionMax_Occurs = QtWidgets.QAction(MainWindow)
        self.actionMax_Occurs.setObjectName("actionMax_Occurs")
        self.actionTYPE = QtWidgets.QAction(MainWindow)
        self.actionTYPE.setObjectName("actionTYPE")
        self.actionNew_Folder = QtWidgets.QAction(MainWindow)
        self.actionNew_Folder.setObjectName("actionNew_Folder")
        self.menuMenu.addAction(self.actionUpload)
        self.menuMenu.addAction(self.actionNew_Folder)
        self.menuMenu.addAction(self.actionPassive)
        self.menuMenu.addAction(self.actionPort)
        self.menuMenu.addAction(self.actionTYPE)
        self.menuMenu.addAction(self.actionSYSTEM)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client by WSJ"))
        self.cmdBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"><br /></p></body></html>"))
        item = self.folderWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.folderWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.folderWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.folderWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.folderWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Permissions"))
        self.label_5.setText(_translate("MainWindow", "Remote Path:"))
        self.navigationBar.setText(_translate("MainWindow", "/"))
        self.goButton.setText(_translate("MainWindow", "CD TO"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.ipInput.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.portInput.setText(_translate("MainWindow", "21"))
        self.label_3.setText(_translate("MainWindow", "User"))
        self.userInput.setText(_translate("MainWindow", "anonymous"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.passwordInput.setText(_translate("MainWindow", "password"))
        item = self.folderWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.folderWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.folderWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.folderWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.folderWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Permissions"))
        self.label_6.setText(_translate("MainWindow", "Local Path:"))
        self.goButton_2.setText(_translate("MainWindow", "CD TO"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionPassive.setText(_translate("MainWindow", "PASV MODE"))
        self.actionPort.setText(_translate("MainWindow", "PORT MODE"))
        self.actionSYSTEM.setText(_translate("MainWindow", "SYSTEM"))
        self.actionUpload.setText(_translate("MainWindow", "Upload File"))
        self.actionMax_Occurs.setText(_translate("MainWindow", "Max Occurs"))
        self.actionTYPE.setText(_translate("MainWindow", "TYPE"))
        self.actionNew_Folder.setText(_translate("MainWindow", "New Folder"))

