# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vincent/OneDrive - mails.tsinghua.edu.cn/习习/19秋/计算机网络/project2/TASK-2/Client/src/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 576)
        MainWindow.setMinimumSize(QtCore.QSize(1123, 576))
        MainWindow.setMaximumSize(QtCore.QSize(1123, 576))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setupBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setupBtn.setGeometry(QtCore.QRect(840, 70, 112, 32))
        self.setupBtn.setObjectName("setupBtn")
        self.playBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playBtn.setGeometry(QtCore.QRect(840, 120, 112, 32))
        self.playBtn.setObjectName("playBtn")
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setGeometry(QtCore.QRect(840, 170, 112, 32))
        self.pauseBtn.setObjectName("pauseBtn")
        self.tearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tearBtn.setGeometry(QtCore.QRect(840, 220, 111, 32))
        self.tearBtn.setObjectName("tearBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 800, 450))
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnx15 = QtWidgets.QPushButton(self.centralwidget)
        self.btnx15.setGeometry(QtCore.QRect(840, 325, 112, 32))
        self.btnx15.setObjectName("btnx15")
        self.btnx05 = QtWidgets.QPushButton(self.centralwidget)
        self.btnx05.setGeometry(QtCore.QRect(840, 425, 112, 32))
        self.btnx05.setObjectName("btnx05")
        self.btnx10 = QtWidgets.QPushButton(self.centralwidget)
        self.btnx10.setGeometry(QtCore.QRect(840, 375, 112, 32))
        self.btnx10.setObjectName("btnx10")
        self.Slider = QtWidgets.QSlider(self.centralwidget)
        self.Slider.setGeometry(QtCore.QRect(10, 510, 800, 21))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(850, 290, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(850, 30, 81, 31))
        self.label_3.setObjectName("label_3")
        self.videoList = QtWidgets.QListView(self.centralwidget)
        self.videoList.setGeometry(QtCore.QRect(960, 70, 151, 411))
        self.videoList.setObjectName("videoList")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(960, 30, 81, 31))
        self.label_4.setObjectName("label_4")
        self.lyrLabel = QtWidgets.QLabel(self.centralwidget)
        self.lyrLabel.setGeometry(QtCore.QRect(20, 473, 781, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lyrLabel.sizePolicy().hasHeightForWidth())
        self.lyrLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lyrLabel.setFont(font)
        self.lyrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lyrLabel.setObjectName("lyrLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WPlayer"))
        self.setupBtn.setText(_translate("MainWindow", "Setup"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.tearBtn.setText(_translate("MainWindow", "Teardown"))
        self.btnx15.setText(_translate("MainWindow", "X1.5"))
        self.btnx05.setText(_translate("MainWindow", "X0.5"))
        self.btnx10.setText(_translate("MainWindow", "X1.0"))
        self.label_2.setText(_translate("MainWindow", "Play Speed:"))
        self.label_3.setText(_translate("MainWindow", "Control:"))
        self.label_4.setText(_translate("MainWindow", "Video List:"))
        self.lyrLabel.setText(_translate("MainWindow", "暂无字幕..."))

